# Generated by Django 5.2.7 on 2025-12-05 12:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField()),
                ('categoria', models.CharField(blank=True, max_length=100, null=True)),
                ('formato', models.CharField(choices=[('presencial', 'Presencial'), ('remoto', 'Remoto')], max_length=20)),
                ('data', models.DateField()),
                ('hora', models.TimeField()),
                ('link', models.URLField(blank=True, null=True)),
                ('requisitos', models.TextField(blank=True, null=True)),
                ('imagem_url', models.URLField(blank=True, null=True)),
                ('horas', models.IntegerField(default=0)),
                ('local', models.CharField(blank=True, max_length=200, null=True)),
                ('organizador', models.CharField(blank=True, max_length=200, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('admin_criador', models.BooleanField(default=False)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('matricula', models.CharField(blank=True, max_length=20, null=True)),
                ('curso', models.CharField(blank=True, max_length=100, null=True)),
                ('horas_completadas', models.IntegerField(default=0)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
