# Generated by Django 5.2.9 on 2025-12-07 20:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_comprovante'),
    ]

    operations = [
        migrations.AddField(
            model_name='comprovante',
            name='categoria_sugerida',
            field=models.CharField(choices=[('tecnologia', 'Tecnologia'), ('seguranca', 'Segurança'), ('inovacao', 'Inovação'), ('analise', 'Análise'), ('robotica', 'Robótica'), ('outros', 'Outros')], default='outros', max_length=20),
        ),
        migrations.AddField(
            model_name='comprovante',
            name='evento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.evento'),
        ),
        migrations.AddField(
            model_name='comprovante',
            name='justificativa',
            field=models.TextField(blank=True, null=True),
        ),
    ]
