# Generated by Django 5.2.9 on 2025-12-07 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_comprovante_categoria_sugerida_comprovante_evento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='horas_pendentes',
            field=models.IntegerField(default=0),
        ),
    ]
