# Generated by Django 5.2.9 on 2025-12-09 11:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_comprovante_categoria_sugerida_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comprovante',
            name='categoria_sugerida',
            field=models.CharField(choices=[('evento_academico', 'Evento Acadêmico'), ('extensao', 'Extensão'), ('cultura', 'Cultura'), ('carreira', 'Carreira'), ('esporte', 'Esporte'), ('outros', 'Outros')], default='outros', max_length=20),
        ),
        migrations.AddField(
            model_name='comprovante',
            name='evento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.evento'),
        ),
        migrations.AddField(
            model_name='comprovante',
            name='justificativa',
            field=models.TextField(blank=True, null=True),
        ),
    ]
