# Generated by Django 5.2.7 on 2025-11-28 19:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meu_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='curso',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='foto_perfil',
        ),
        migrations.AddField(
            model_name='perfil',
            name='biografia',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='perfil',
            name='data_atualizacao',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='perfil',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='perfil',
            name='departamento',
            field=models.CharField(blank=True, choices=[('COMP', 'Ciência da Computação'), ('ENG', 'Engenharia'), ('MAT', 'Matemática'), ('DES', 'Design')], max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='perfil',
            name='linkedin',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='perfil',
            name='matricula',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='perfil',
            name='tipo_usuario',
            field=models.CharField(choices=[('EST', 'Estudante'), ('PROF', 'Professor'), ('ADMIN', 'Administrador')], default='EST', max_length=5),
        ),
    ]
