# Generated by Django 5.2.7 on 2025-11-28 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meu_app', '0002_remove_perfil_curso_remove_perfil_foto_perfil_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='biografia',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='data_atualizacao',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='data_criacao',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='departamento',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='linkedin',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='matricula',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='tipo_usuario',
        ),
        migrations.AddField(
            model_name='perfil',
            name='curso',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
